parameters:
    heidi_alpen.menu_builder.class: HeidiAlpen\SiteBundle\Menu\MenuBuilder
    heidi_alpen.menu.class: Knp\Menu\MenuItem

services:
    heidi_alpen.menu_builder:
        class: %heidi_alpen.menu_builder.class%
        arguments: ["@knp_menu.factory", "@security.context"]

    heidi_alpen.menu.main:
        class: %heidi_alpen.menu.class%
        factory_service: heidi_alpen.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu }
    
    heidi_alpen.menu.mobile:
        class: %heidi_alpen.menu.class%
        factory_service: heidi_alpen.menu_builder
        factory_method: createMobileMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mobileMenu }

    jms_i18n_routing.locale_listener:
        class: HeidiAlpen\SiteBundle\Listener\JMSI18nRoutingLocaleListener
        tag:
            - { name: Kernel.event_subscriber }
        argument:
            - { type: service, id: jms_i18n_routing.locale_resolver }
            - { type: service, id: router }